
package com.example.app.soapserver.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "HelloServiceEndpoint", targetNamespace = "http://endpoint.soapserver.app.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloServiceEndpoint {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "executeHello", targetNamespace = "http://endpoint.soapserver.app.example.com/", className = "com.example.app.soapserver.endpoint.ExecuteHello")
    @ResponseWrapper(localName = "executeHelloResponse", targetNamespace = "http://endpoint.soapserver.app.example.com/", className = "com.example.app.soapserver.endpoint.ExecuteHelloResponse")
    public String executeHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
